larch: (profiles) larch0 now called with mount-point as argument
i18n - minor updates

diff --git a/larch7/abs/larch-profiles/profiles/xmini/cd-root/larch/copy/larch0 b/larch7/abs/larch-profiles/profiles/xmini/cd-root/larch/copy/larch0
--- a/larch7/abs/larch-profiles/profiles/xmini/cd-root/larch/copy/larch0
+++ b/larch7/abs/larch-profiles/profiles/xmini/cd-root/larch/copy/larch0
@@ -1,7 +1,15 @@
-# This is a script 'sourced' from the installation script larch-tidy.
+# This is a script called from the installation script fix-system2.
 # Its purpose is to remove custom live-only stuff from a just-installed
 # system.
-# ${INSTALL} is the path to the installed system root directory.
+
+# $1 is the path to the installed system root directory.
+
+INSTALL=$1
+if [ -z "${INSTALL}" ] || [ ! -f /etc/rc.conf ]; then
+    echo "ERROR: larch0 installation adjustments failed:"
+    echo "      Please check installation mount point (${INSTALL})"
+    exit 1
+fi
 
 rm -f "${INSTALL}/root/Desktop/Install Arch Linux.desktop"
 rm -f "${INSTALL}/etc/rc.d/functions.d/larch-autologin"
@@ -16,9 +24,12 @@ fi
 # start gdm from rc.conf
 sed -i '/^DAEMONS=/ s|!gdm|@gdm|' ${INSTALL}/etc/rc.conf
 
-# Adjust xorg.conf for no DRI if necessary
+# Adjust xorg.conf for vesa driver or no DRI if necessary
 for x in $(cat /proc/cmdline); do
-    if [ "${x}" = "nodri" ]; then
+    if [ "${x}" = "xvesa" ]; then
+        sed 's|^#xvesa||' -i ${INSTALL}/etc/X11/xorg.conf
+        break
+    elif [ "${x}" = "nodri" ]; then
         sed 's|^#nodri||' -i ${INSTALL}/etc/X11/xorg.conf
         break
     fi
