create-iso updated

diff --git a/larch7/larch/run/create-iso b/larch7/larch/run/create-iso
--- a/larch7/larch/run/create-iso
+++ b/larch7/larch/run/create-iso
@@ -3,11 +3,11 @@
 # create-iso
 
 # To build a bootable (isolinux) CD from a larch USB-stick with
-# syslinux boot. This creates the ISO-file.
+# syslinux or grub boot. This creates the ISO-file.
 
-# $1 is the USB-stick's mount-point.
+# $1 is the USB-stick's mount-point (default = /.livesys/medium).
 
-# Author: Michael Towers [ gradgrind at online dot de ]
+# Author: Michael Towers (larch42 at googlemail dot com)
 #
 # This file is part of the larch project.
 #
@@ -26,13 +26,7 @@
 #    51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 #
 #----------------------------------------------------------------------------
-# 2009.08.15
-
-echo "WARNING! This is old stuff, not yet updated."
-echo "Don't use it with larch-7."
-echo
-exit
-
+# 2009.09.15
 
 # You might need to adjust this
 ISOLINUXBIN=/usr/lib/syslinux/isolinux.bin
@@ -83,7 +77,7 @@ mkiso ()
         -no-emul-boot -boot-load-size 4 -boot-info-table \
         -input-charset=UTF-8 \
         -publisher "designed by gradgrind, licence: GPL" \
-        -A "larch-5" \
+        -A "larch-7" \
         -o "larch.iso" "${CDDATA}"
 
     if [ $? -eq 0 ]; then
@@ -102,25 +96,43 @@ fi
 
 CDDATA=$( pwd )/bootcd
 rm -rf ${CDDATA}
-cp -r ${MP} .
-mv $( basename ${MP} ) ${CDDATA}
+mkdir -p ${CDDATA}/larch
+if [ -d ${MP}/syslinux ]; then
+    cp -r ${MP}/syslinux ${CDDATA}/isolinux
+    mv ${CDDATA}/isolinux/syslinux.cfg ${CDDATA}/isolinux/isolinux.cfg
+    isoarg="-b isolinux/isolinux.bin -c isolinux/isolinux.boot"
+    cp ${ISOLINUXBIN} ${CDDATA}/isolinux
+    # CDs are only bootable using the search method
+    sed "s|\(initrd=larch.img .*\) uuid=[^ ]*|\1|g" -i ${CDDATA}/isolinux/isolinux.cfg
+    sed "s|\(initrd=larch.img .*\) label=[^ ]*|\1|g" -i ${CDDATA}/isolinux/isolinux.cfg
+    sed "s|\(initrd=larch.img .*\) root=[^ ]*|\1|g" -i ${CDDATA}/isolinux/isolinux.cfg
+elif [ -d ${MP}/boot ]; then
+    cp -r ${MP}/boot ${CDDATA}
+    isoarg="-b boot/grub/stage2_eltorito"
+    # CDs are only bootable using the search method
+    sed "s|\(larch.kernel .*\) uuid=[^ ]*|\1|g" -i ${CDDATA}/boot/grub/menu.lst
+    sed "s|\(larch.kernel .*\) label=[^ ]*|\1|g" -i ${CDDATA}/boot/grub/menu.lst
+    sed "s|\(larch.kernel .*\) root=[^ ]*|\1|g" -i ${CDDATA}/boot/grub/menu.lst
+else
+    echo "ERROR: No syslinux or boot directory"
+    exit 1
+fi
 
-rm -f ${CDDATA}/ldlinux.sys
-mv ${CDDATA}/syslinux ${CDDATA}/isolinux
-mv ${CDDATA}/isolinux/syslinux.cfg ${CDDATA}/isolinux/isolinux.cfg
-
-if [ -f ${CDDATA}/overlay.ovl_ ]; then
-    # Use the updated overlay(s)
-    mv -f ${CDDATA}/overlay.ovl_ ${CDDATA}/overlay.ovl
-    if [ -f ${CDDATA}/mods.sqf_ ]; then
-        mv -f ${CDDATA}/mods.sqf_ ${CDDATA}/mods.sqf
+for f in $( ls ${MP}/larch | grep -v "\.sqf" ); do
+    cp -r ${f} ${CDDATA}/larch
+done
+cp ${CDDATA}/larch/system.sqf ${CDDATA}/larch
+# Use the updated overlay(s) ('_' suffix) if they are present.
+for f in mods filter; do
+    if [ -f ${MP}/larch/${f}.sqf_ ]; then
+        cp ${MP}/larch/${f}.sqf_ ${CDDATA}/larch/${f}.sqf
+    else
+        cp ${MP}/larch/${f}.sqf ${CDDATA}/larch
     fi
 fi
-# Remove any backup overlay
-rm -f ${CDDATA}/overlay.ovl~
+done
+
 # Session saving stuff is irrelevant on a CD
 rm -f ${CDDATA}/larch/save
 
-cp ${ISOLINUXBIN} ${CDDATA}/isolinux
-
-mkiso "-b isolinux/isolinux.bin -c isolinux/isolinux.boot"
+mkiso "${isoarg}"
